### ISSUE TITLE
probleme today

### ISSUE THREAD

**Issue by Ricky834** [timewasted/xbmc-nhl-gamecenter#7]
script failed 

```
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                        Error Type: <class 'xml.parsers.expat.ExpatError'>
                                        Error Contents: mismatched tag: line 20, column 2
                                        Traceback (most recent call last):
                                          File "/storage/.xbmc/addons/plugin.video.xbmc-nhl-gamecenter/main.py", line 504, in <module>
                                            game_center.MODE_list(today_only)
                                          File "/storage/.xbmc/addons/plugin.video.xbmc-nhl-gamecenter/main.py", line 317, in MODE_list
                                            games = self.game_center.get_games_list(today_only)
                                          File "/storage/.xbmc/addons/plugin.video.xbmc-nhl-gamecenter/resources/lib/nhlgc.py", line 300, in get_games_list
                                            r_xml = xmltodict.parse(r.text)
                                          File "/storage/.xbmc/addons/script.module.xmltodict/lib/xmltodict.py", line 248, in parse
                                            parser.Parse(xml_input, True)
                                        ExpatError: mismatched tag: line 20, column 2
                                        -->End of Python script error report<--
```

**Comment by oneklc** [comment]
I'm seeing the same thing:
With Debug on here is the error in the logs:
    `
21:37:25 T:140648183236352   ERROR: /home/klc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
21:37:25 T:140648183236352   ERROR: /home/klc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
21:37:27 T:140648183236352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.parsers.expat.ExpatError'>
                                            Error Contents: mismatched tag: line 20, column 2
                                            Traceback (most recent call last):
                                              File "/home/klc/.kodi/addons/plugin.video.nhl-gamecenter-live/main.py", line 504, in <module>
                                                game_center.MODE_list(today_only)
                                              File "/home/klc/.kodi/addons/plugin.video.nhl-gamecenter-live/main.py", line 317, in MODE_list
                                                games = self.game_center.get_games_list(today_only)
                                              File "/home/klc/.kodi/addons/plugin.video.nhl-gamecenter-live/resources/lib/nhlgc.py", line 300, in get_games_list
                                                r_xml = xmltodict.parse(r.text)
                                              File "/home/klc/.kodi/addons/script.module.xmltodict/lib/xmltodict.py", line 248, in parse
                                                parser.Parse(xml_input, True)
                                            ExpatError: mismatched tag: line 20, column 2
                                            -->End of Python script error report<--
`

**Comment by myoung34** [comment]
Same here on a rasp pi running latest openelec.

Looks related to https://github.com/OpenELEC/OpenELEC.tv/issues/4555 ?

**Comment by ralyodio** [comment]
I'm also getting this.

**Comment by myoung34** [comment]
@timewasted any updates to this and #4 ? Your plugin is the only reason I use my kodi =)

**Comment by ralyodio** [comment]
@myoung34 i've been using this one instead: https://github.com/eracknaphobia/plugin.video.nhlgcl
