### ISSUE TITLE
Too many usage attempts

### ISSUE THREAD

**Issue by calmarc** [timewasted/xbmc-nhl-gamecenter#8]
hi,
I have the lastest (today) git version.

I get following error, when trying to play a recent game: 
11:01:06  99.151176 T:1731195808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.nhlgc.LogicError'>
                                            Error Contents: Sign-on restriction: Too many usage attempts[CR](function: get_event_info)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/xbmc-nhl-gamecenter-master/main.py", line 461, in <module>
                                                game_center.MODE_view_options(game)
                                              File "/storage/.kodi/addons/xbmc-nhl-gamecenter-master/main.py", line 347, in MODE_view_options
                                                event_info = self.game_center.get_event_info(game['event_id'])
                                              File "/storage/.kodi/addons/xbmc-nhl-gamecenter-master/resources/lib/nhlgc.py", line 442, in get_event_info
                                                raise self.LogicError(fn_name, r_json['status_message'])
                                            LogicError: Sign-on restriction: Too many usage attempts[CR](function: get_event_info)
                                            -->End of Python script error report<--
11:01:06  99.154518 T:1962463232   DEBUG: ------ Window Init (DialogKaiToast.xml) ------

(on a rasbperry 3, openelec 6.95.2.7.0)

I tried to login via the normal webbrowser, there it works.

cheers and thanks,
calmar

**Comment by calmarc** [comment]
however now it works again.. hm. let's see how long

**Comment by calmarc** [comment]
again:  Error Type: <class 'resources.lib.nhlgc.LogicError'>
                                            Error Contents: Sign-on restriction: Too many usage attempts[CR](function: get_event_info)
